### PR TITLE
fix: add windows high contrast media query to our components

### LINKED ISSUE #2089: Buttons do not show hover state, and disabled state is wrong, in HC mode
**Describe the bug; what happened?**
accent, neutral, outline, stealth 
- does not show backgrounds on hover or active state
- cannot see disabled state
 
**What are the steps to reproduce the issue?**
1. Turn on Windows high contrast
2. Open Edge browser  (I use Spartan Edge)
3. Go to https://explore.fast.design/components/button
4. Hover over button, you will see no indication that it is hovered
5. Now  check on "disabled", the button is too dimmed

**What behavior did you expect?**
- When hovering, we should see a high contrast background and text changed
- When disabled, the button should be 100% opacity

**If applicable, provide screenshots:**
hover
image

disabled
image

### LINKED ISSUE #2090: Action toggle, trigger and call to action need high contrast pass
**Describe the bug; what happened?**
- Both action-toggle, action-trigger and call-to-action, do not have backgrounds when hovering over them and their disabled states are to dimmed.
- You also cannot see the icons
**What are the steps to reproduce the issue?**

1. Turn on Windows high contrast
2. Open Edge browser (I use Spartan Edge)
3. Go to:
https://explore.fast.design/components/action-toggle
https://explore.fast.design/components/action-trigger
https://explore.fast.design/components/call-to-action
4. Hover over button, you will see no indication that it is hovered
5. Now check on "disabled", the button is too dimmed

**What behavior did you expect?**
When hovering, we should see a high contrast background and text changed
When disabled, the button should be 100% op

**If applicable, provide screenshots:**
hover
image
image
image

disabled
image
image
image

### LINKED ISSUE #2092: Auto suggest and auto suggest option are broken in high contrast mode
**Describe the bug; what happened?**
There are no high contrast background on hover and it disabled is too dimmed

**What are the steps to reproduce the issue?**
1. Turn on Windows high contrast
2. Open Edge browser (I use Spartan Edge)
3. Go to https://explore.fast.design/components/auto-suggest
4. Hover over input, you will see no indication that it is hovered
5. Select  the input you will auto suggest options with borders

**What behavior did you expect?**
- There should hover backgrounds on both auto suggest and auto suggest options
- No borders around auto suggest options
- Disabled is too dimmed

**If applicable, provide screenshots:**
image
image
image

### LINKED ISSUE #2094: Card is missing outline in high contrast mode
**Describe the bug; what happened?**
There are no outlines indicating if there is a card.

**What are the steps to reproduce the issue?**
1. Turn on Windows high contrast
2. Open Edge browser (I use Spartan Edge)
3. Go to https://explore.fast.design/components/card
4. Observe and see no card, just an image

**What behavior did you expect?**
There should be an outline around the Card
The bound of the Card should be mapped to the "Text" keyword.

**If applicable, provide screenshots:**
Default mode
image

High contrast mode
image

### LINKED ISSUE #2095: Checkbox and Radio have no hover indicator in high contrast
**Describe the bug; what happened?**
For both Radio and Checkbox, when in selected state, and hovering over the input or label, there are no visual changes to the input

**What are the steps to reproduce the issue?**
1. Turn on Windows high contrast
2. Open Edge browser (I use Spartan Edge)
3. Go to:
https://explore.fast.design/components/checkbox
https://explore.fast.design/components/radio
4. Select input and hover on and off of component
5. Observe that nothing changes
6. Turn on disabled, the component is too dimmed

**What behavior did you expect?**
When in selected state, it should visually be in high contrast "HighlightText" mode and when hover it should be in "ButtonText" mode 

**If applicable, provide screenshots:**
selected
image
image

disabled
image
image

### LINKED ISSUE #2096: Context menu and item has no hover state in high contrast
**Describe the bug; what happened?**
When hovering over the context item inside context menu, there is no background hover

**What are the steps to reproduce the issue?**
1. Turn on Windows high contrast
2. Open Edge browser (I use Spartan Edge)
3. Go to https://explore.fast.design/components/context-menu
4. Hover over the context item

**What behavior did you expect?**
The items should be highlighted on hover. When the item is disabled, it should not be dimmed.
There should also be no borders around items

**If applicable, provide screenshots:**
image

disabled
image

### LINKED ISSUE #2097: Pivot has no hover and select indicators when in high contrast
**Describe the bug; what happened?**
When hovering over an item, you don't see any type of hover. There are no visual indication on which pivot item is selected.

**What are the steps to reproduce the issue?**
1. Turn on Windows high contrast
2. Open Edge browser (I use Spartan Edge)
3. Go to https://explore.fast.design/components/pivot
4. Hover over the pivot item and select anyone of them
5. Observe that nothing changes, visually

**What behavior did you expect?**
We should see a hover state and a selected state on the item selected
Pivot should be mapped to "ButtonText" in high contrast

**If applicable, provide screenshots:**
image

### LINKED ISSUE #2098: Select and Select options are broken in high contrast
**Describe the bug; what happened?**
When hovering over Select, it does nothing visually, and when you click open the options, hover and select does not have any visual hover and select queues.

**What are the steps to reproduce the issue?**
1. Turn on Windows high contrast
2. Open Edge browser (I use Spartan Edge)
3. Go to https://explore.fast.design/components/select
4. Hover over Select and click to open option items
5. Observe and see that nothing changes when hovering and selecting.
6. Turn on "disabled". It is too dim

**What behavior did you expect?**
We should be seeing items highlighted when hovering and selecting

**If applicable, provide screenshots:**
image

### LINKED ISSUE #2099: Text action, text area and text field, the disabled state is too dim
**Describe the bug; what happened?**
When text-action, text-area, and text-field, are disabled, the components are not using disabled high contrast standard

**What are the steps to reproduce the issue?**
1. Turn on Windows high contrast
2. Open Edge browser (I use Spartan Edge)
3. Go to:
https://explore.fast.design/components/text-action
https://explore.fast.design/components/text-area
https://explore.fast.design/components/text-field
4. Check on disabled
5. Observe text-action, text-area, or text-field, they are too dim

**What behavior did you expect?**
Should be at 100% opacity and mapped to disabled keyword

**If applicable, provide screenshots:**
disabled
image
image
image

### LINKED ISSUE #2100: Toggle indicator, in high contrast, on hover, is wrong in selected state and disable is not using HC color
**Describe the bug; what happened?**
When toggle is switched to "On", and when hovering, the input shows the wrong high contrast color. 
The label is using the wrong keyword.

**What are the steps to reproduce the issue?**
1. Turn on Windows high contrast
2. Open Edge browser (I use Spartan Edge)
3. Go to https://explore.fast.design/components/toggle
4. Toggle to On
5. Hover over toggle input
6. Observe and see that the input changes to "Background" instead of "SelectedText"
7. Turn on disabled, observe that it is dimmed and not using "DisabledText" keyword

**What behavior did you expect?**
The input should also change when hovering on the label and the toggle be "SelectedText"
The label should also me mapped to "ButtonText" keyword

**If applicable, provide screenshots:**
toggle selected
image

toggle selected, on hover
image

disabled
image

### LINKED ISSUE #2104: High contrast disabled state are all hard to see
**Describe the bug; what happened?**
When our components are disabled they could be using the correct disabled color, but the low opacity makes it hard what it is.
 
**What are the steps to reproduce the issue?**
1. Turn on Windows high contrast
2. Open Edge browser (I use Spartan Edge)
3. Go to: https://explore.fast.design/components
4. On any component, select disabled, on any of the components

**What behavior did you expect?**
We should see the components at 100% opacity

**If applicable, provide screenshots:**
some examples:
image
image
image
image
image

### PR DESCRIPTION
**Pull request by khamudom**
# Description
Worked close with Rory to make sure our FAST components to meet high contrast standard.

- In the component's styles file, I added Windows high contrast media query `@media (-ms-high-contrast: active)`, covering scenarios like rest, hover, active, disabled states.
- Updated keyboard focus for high contrast.

The CSS style values used are:
- ButtonText: foreground of button
- ButtonFace: background of button
- HighlightText: foreground on select
- Highlight: background on select
- GrayText: disable state
- LinkText: hyperlink color
- WindowText: foreground color
- Background: background color
 
set `"-ms-high-contrast-adjust": "none",` to remove text back plate, on text with backgrounds that are overwritten.
 
edit:
Added a `high-contrast` utilities file, and created functions to use in places where there are common patterns across the components. Specifically among our buttons and field inputs.

## Motivation & context

We need to make sure high contrast remains consistent, from system to browser, when users enable high contrast in Windows.

closes #2104
closes #2100 
closes #2099 
closes #2098 
closes #2097 
closes #2096 
closes #2095 
closes #2094 
closes #2092 
closes #2090 
closes #2089 

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/en/contributing/standards) for this project.

### CODE REVIEW

File: packages/fast-components-styles-msft/src/checkbox/index.ts [hunk 1]
```diff
@@ -43,7 +43,8 @@ const indicatorSvg: DesignSystemResolver<string> = (
         neutralForegroundRest(designSystem)
     )}" fill-rule="evenodd" clip-rule="evenodd" d="M8.143 12.6697L15.235 4.5L16.8 5.90363L8.23812 15.7667L3.80005 11.2556L5.27591 9.7555L8.143 12.6697Z"/></svg>`;
 };
-const indicatorSvgHc: string = `<svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill="ButtonHighlight" fill-rule="evenodd" clip-rule="evenodd" d="M8.143 12.6697L15.235 4.5L16.8 5.90363L8.23812 15.7667L3.80005 11.2556L5.27591 9.7555L8.143 12.6697Z"/></svg>`;
+const indicatorSvgHc: string = `<svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill="HighlightText" fill-rule="evenodd" clip-rule="evenodd" d="M8.143 12.6697L15.235 4.5L16.8 5.90363L8.23812 15.7667L3.80005 11.2556L5.27591 9.7555L8.143 12.6697Z"/></svg>`;
+const indicatorSvgHcHover: string = `<svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill="Highlight" fill-rule="evenodd" clip-rule="evenodd" d="M8.143 12.6697L15.235 4.5L16.8 5.90363L8.23812 15.7667L3.80005 11.2556L5.27591 9.7555L8.143 12.6697Z"/></svg>`;
```
Comment (bheston) [inline packages/fast-components-styles-msft/src/checkbox/index.ts]: The only thing that is different in all three indicators is the color. We should remove the color from the svg and apply it through css in all cases.

File: packages/fast-components-styles-msft/src/dialog/index.ts [hunk 2]
```diff
@@ -18,6 +18,9 @@ const styles: ComponentStyles<DialogClassNameContract, DesignSystem> = (
             '&[aria-hidden="false"]': {
                 display: "block",
             },
+            "@media (-ms-high-contrast:active)": {
+                border: "1px solid WindowText",
```
Comment (bheston) [inline packages/fast-components-styles-msft/src/dialog/index.ts]: Probably use outlineWidth to be consistent.

File: packages/fast-components-styles-msft/src/flyout/index.ts [hunk 3]
```diff
@@ -16,6 +16,9 @@ const styles: ComponentStyles<FlyoutClassNameContract, DesignSystem> = {
         '&[aria-hidden="false"]': {
             display: "block",
         },
+        "@media (-ms-high-contrast:active)": {
+            border: "1px solid WindowText",
```
Comment (bheston) [inline packages/fast-components-styles-msft/src/flyout/index.ts]: outlineWidth

File: packages/fast-components-styles-msft/src/number-field/index.ts [hunk 4]
```diff
@@ -6,6 +6,7 @@ import {
     directionSwitch,
     format,
     localizeSpacing,
+    toPx,
```
Comment (bheston) [inline packages/fast-components-styles-msft/src/number-field/index.ts]: Needed?

File: packages/fast-components-styles-msft/src/patterns/input-field.ts [hunk 5]
```diff
@@ -56,9 +60,17 @@ export function inputFieldStyles(
             boxShadow: format<DesignSystem>("0 0 0 1px {0} inset", neutralFocus),
             borderColor: neutralFocus,
             outline: "none",
+            "@media (-ms-high-contrast:active)": {
+                boxShadow: format<DesignSystem>("0 0 0 1px ButtonText inset"),
```
Comment (bheston) [inline packages/fast-components-styles-msft/src/patterns/input-field.ts]: focusOutlineWidth - outlineWidth

File: packages/fast-components-styles-msft/src/radio/index.ts [hunk 6]
```diff
@@ -74,7 +74,13 @@ const styles: ComponentStyles<RadioClassNameContract, DesignSystem> = {
         ...applyFocusVisible({
             boxShadow: format<DesignSystem>("0 0 0 1px {0} inset", neutralFocus),
             borderColor: neutralFocus,
+            "@media (-ms-high-contrast:active)": {
+                boxShadow: format<DesignSystem>("0 0 0 2px ButtonText"),
```
Comment (bheston) [inline packages/fast-components-styles-msft/src/radio/index.ts]: Any way to keep this inside like non-HC?

File: packages/fast-components-styles-msft/src/flyout/index.ts (hunk 3 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/flyout/index.ts]: updated

File: packages/fast-components-styles-msft/src/number-field/index.ts (hunk 4 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/number-field/index.ts]: removed

File: packages/fast-components-styles-msft/src/patterns/input-field.ts (hunk 5 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/patterns/input-field.ts]: updated

File: packages/fast-components-styles-msft/src/radio/index.ts (hunk 6 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/radio/index.ts]: moved focused inside

File: packages/fast-components-styles-msft/src/dialog/index.ts (hunk 2 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/dialog/index.ts]: updated

File: packages/fast-components-styles-msft/src/checkbox/index.ts [hunk 7]
```diff
@@ -110,13 +121,45 @@ const styles: ComponentStyles<CheckboxClassNameContract, DesignSystem> = {
...
+            },
+        },
+        "& $checkbox_input": {
+            "@media (-ms-high-contrast:active)": {
+                background: "Highlight",
+            },
+            "&:hover": {
                 "@media (-ms-high-contrast:active)": {
-                    background: `url('data:image/svg+xml;utf8,${indicatorSvgHc}')`,
+                    background: "HighlightText",
```
Comment (bheston) [inline packages/fast-components-styles-msft/src/checkbox/index.ts]: Does this not need to be the checkmark svg?

Comment (bheston) [reply packages/fast-components-styles-msft/src/checkbox/index.ts]: Never mind.

File: packages/fast-components-styles-msft/src/accent-button/index.ts [hunk 8]
```diff
@@ -21,6 +22,16 @@ const styles: ComponentStyles<AccentButtonClassNameContract, DesignSystem> = {
         background: accentFillRest,
         "&:hover:enabled": {
             background: accentFillHover,
+            "@media (-ms-high-contrast:active)": {
+                background: "HighlightText",
```
[the remark this answers is not in the document]
Comment (chrisdholt) [reply packages/fast-components-styles-msft/src/accent-button/index.ts]: @janechu should we consider constants instead (per @nicholasrice's performance work as of late)?

File: packages/fast-components-styles-msft/src/action-trigger/index.ts [hunk 9]
```diff
@@ -42,18 +42,37 @@ const styles: ComponentStyles<ActionTriggerClassNameContract, DesignSystem> = {
     actionTrigger__primary: {
         "& $actionTrigger_glyph": {
             fill: accentForegroundCut,
+            "@media (-ms-high-contrast:active)": {
+                fill: "HighlightText",
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/action-trigger/index.ts]: created function in high contrast utilities file

File: packages/fast-components-styles-msft/src/accent-button/index.ts (hunk 8 above)
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/accent-button/index.ts]: created an enum for the high contrast color values

File: packages/fast-components-styles-msft/src/accent-button/index.ts [hunk 10]
```diff
@@ -21,6 +22,16 @@ const styles: ComponentStyles<AccentButtonClassNameContract, DesignSystem> = {
...
+                borderColor: "Highlight",
+                color: "Highlight",
+            },
+            "& $button_beforeContent, & $button_afterContent": {
+                "@media (-ms-high-contrast:active)": {
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/accent-button/index.ts]: created a const called `highContrastSelector` for the media query

File: packages/fast-components-styles-msft/src/utilities/high-contrast.ts [hunk 11]
```diff
@@ -0,0 +1,219 @@
...
+export function applyHighContrastDisabledColor(): CSSRules<DesignSystem> {
+    return {
+        [highContrastSelector]: {
+            opacity: "1",
+            color: HighContrastColor.disabledText,
+        },
+    };
+}
+
+export function applyHighContrastDisabledFill(): CSSRules<DesignSystem> {
```
Comment (bheston) [inline packages/fast-components-styles-msft/src/utilities/high-contrast.ts]: Can fill and color go together and be "foreground"? See related notes below.

File: packages/fast-components-styles-msft/src/utilities/high-contrast.ts [hunk 12]
```diff
@@ -0,0 +1,219 @@
...
+export function applyHighContrastBorder(): CSSRules<DesignSystem> {
+    return {
+        [highContrastSelector]: {
+            background: HighContrastColor.buttonBackground,
+            border: format("{0} solid ButtonText", toPx<DesignSystem>(outlineWidth)),
+        },
+    };
+}
+
+export function applyHighContrastAdjustSelectOutline(): CSSRules<DesignSystem> {
```
Comment (bheston) [inline packages/fast-components-styles-msft/src/utilities/high-contrast.ts]: I think you can drop "Adjust" as that's an implementation detail. Maybe standardize on "Selected" (+ed). I think you can drop "Outline" as well as this just happens to be the selected state, for anything whether it has a border or not.

File: packages/fast-components-styles-msft/src/accent-button/index.ts [hunk 13]
```diff
@@ -31,9 +47,33 @@ const styles: ComponentStyles<AccentButtonClassNameContract, DesignSystem> = {
...
+                ...applyHighContrastDisabledBorder(),
+                "& $button_beforeContent, & $button_afterContent": {
+                    ...applyHighContrastDisabledFill(),
+                },
+                "&:hover:enabled": {
+                    ...applyHighContrastDisabledBorder(),
+                    "& $button_beforeContent, & $button_afterContent": {
+                        ...applyHighContrastDisabledFill(),
+                    },
+                },
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/accent-button/index.ts]: In multiple places, where the state is disabled, hover is still effecting the element. This is the reasoning why I set hover.

File: packages/fast-components-styles-msft/src/utilities/high-contrast.ts [hunk 14]
```diff
@@ -0,0 +1,219 @@
...
+    return {
+        [highContrastSelector]: {
+            background: HighContrastColor.selectedText,
+            borderColor: HighContrastColor.selectedBackground,
+            color: HighContrastColor.selectedBackground,
+        },
+    };
+}
+
+export function applyHighContrastAccentSelectedFillHover(): CSSRules<DesignSystem> {
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/utilities/high-contrast.ts]: this is used on a glyph that is inside an accent button. Our Accent button, in rest set, uses the selected colors. On hover, the content and background flips.

File: packages/fast-components-styles-msft/src/utilities/high-contrast.ts [hunk 15]
```diff
@@ -0,0 +1,219 @@
...
+            fill: HighContrastColor.selectedBackground,
+        },
+    };
+}
+
+export function applyHighContrastSelectedHover(): CSSRules<DesignSystem> {
+    return {
+        [highContrastSelector]: {
+            background: HighContrastColor.selectedBackground,
+            borderColor: HighContrastColor.buttonText,
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/utilities/high-contrast.ts]: This is reversed in high contrast, because if our border matches the background, then it will make the button look like it is shrinking

File: packages/fast-components-styles-msft/src/utilities/high-contrast.ts [hunk 16]
```diff
@@ -0,0 +1,219 @@
...
+export function applyHighContrastSelectedColorFill(): CSSRules<DesignSystem> {
+    return {
+        [highContrastSelector]: {
+            color: HighContrastColor.selectedText,
+            fill: HighContrastColor.selectedText,
+        },
+    };
+}
+
+export function applyHighContrastTextBorder(): CSSRules<DesignSystem> {
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/utilities/high-contrast.ts]: our Card, Dialog, Flyout will use this. Components that are not interactive, have no border but have elevation. We want to map them to the text color. Maybe call it `applyHighContrastTextColor`

File: packages/fast-components-styles-msft/src/utilities/high-contrast.ts [hunk 17]
```diff
@@ -0,0 +1,219 @@
...
+            "-ms-high-contrast-adjust": "none",
+        },
+    };
+}
+
+export function applyHighContrastBorder(): CSSRules<DesignSystem> {
+    return {
+        [highContrastSelector]: {
+            background: HighContrastColor.buttonBackground,
+            border: format("{0} solid ButtonText", toPx<DesignSystem>(outlineWidth)),
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/utilities/high-contrast.ts]: updated

File: packages/fast-components-styles-msft/src/utilities/high-contrast.ts [hunk 18]
```diff
@@ -0,0 +1,219 @@
...
+export function applyHighContrastColorFill(): CSSRules<DesignSystem> {
+    return {
+        [highContrastSelector]: {
+            color: HighContrastColor.buttonText,
+            fill: HighContrastColor.buttonText,
+        },
+    };
+}
+
+export function applyHighContrastSelectedColorFill(): CSSRules<DesignSystem> {
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/utilities/high-contrast.ts]: updated to applyHighContrastSelectedForeground

File: packages/fast-components-styles-msft/src/utilities/high-contrast.ts [hunk 19]
```diff
@@ -0,0 +1,219 @@
...
+
+export function applyHighContrastAccentSelectedFillHover(): CSSRules<DesignSystem> {
+    return {
+        [highContrastSelector]: {
+            fill: HighContrastColor.selectedBackground,
+        },
+    };
+}
+
+export function applyHighContrastSelectedHover(): CSSRules<DesignSystem> {
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/utilities/high-contrast.ts]: updated to applyHighContrastSelection

File: packages/fast-components-styles-msft/src/utilities/high-contrast.ts [hunk 20]
```diff
@@ -0,0 +1,219 @@
...
+
+export function applyHighContrastBorderOnlyFocus(): CSSRules<DesignSystem> {
+    return {
+        [highContrastSelector]: {
+            borderColor: HighContrastColor.buttonText,
+        },
+    };
+}
+
+export function applyHighContrastInsetFocus(): CSSRules<DesignSystem> {
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/utilities/high-contrast.ts]: update to applyHighContrastOutlineFocus

File: packages/fast-components-styles-msft/src/utilities/high-contrast.ts (hunk 11 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/utilities/high-contrast.ts]: update to applyHighContrastDisabledForeground

File: packages/fast-components-styles-msft/src/utilities/high-contrast.ts (hunk 12 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/utilities/high-contrast.ts]: updated to applyHighContrastSelected

File: packages/fast-components-styles-msft/src/utilities/high-contrast.ts [hunk 21]
```diff
@@ -0,0 +1,219 @@
...
+
+export function applyHighContrastSelectedFillHover(): CSSRules<DesignSystem> {
+    return {
+        [highContrastSelector]: {
+            fill: HighContrastColor.selectedText,
+        },
+    };
+}
+
+export function applyHighContrastColorFill(): CSSRules<DesignSystem> {
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/utilities/high-contrast.ts]: updated to applyHighContrastForeground

File: packages/fast-components-styles-msft/src/pivot/index.ts [hunk 22]
```diff
@@ -47,17 +52,24 @@ const styles: ComponentStyles<PivotClassNameContract, DesignSystem> = {
...
         "&:active": {
             color: neutralForegroundActive,
         },
         ...applyFocusVisible<DesignSystem>({
             borderColor: neutralFocus,
+            ...applyHighContrastBorderOnlyFocus(),
         }),
+        [highContrastSelector]: {
+            color: "ButtonText",
+            "-ms-high-contrast-adjust": "none",
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/pivot/index.ts]: create applyHighContrastAdjustNone

File: packages/fast-components-styles-msft/src/lightweight-button/index.ts [hunk 23]
```diff
@@ -27,14 +33,18 @@ const styles: ComponentStyles<LightweightButtonClassNameContract, DesignSystem>
             "& $button_contentRegion::before": {
                 background: neutralForegroundRest,
                 height: toPx<DesignSystem>(focusOutlineWidth),
+                [highContrastSelector]: {
+                    background: "ButtonText",
+                    height: toPx<DesignSystem>(focusOutlineWidth),
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/lightweight-button/index.ts]: removed height

File: packages/fast-components-styles-msft/src/checkbox/index.ts [hunk 24]
```diff
@@ -143,6 +190,19 @@ const styles: ComponentStyles<CheckboxClassNameContract, DesignSystem> = {
         ...applyDisabledState(),
         "& $checkbox_input, & $checkbox_label": {
             ...applyCursorDisabled(),
+            ...applyHighContrastDisabledBorder(),
+        },
+        "&:hover": {
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/checkbox/index.ts]: In this case hover is still effecting the disabled state

File: packages/fast-components-styles-msft/src/checkbox/index.ts [hunk 25]
```diff
@@ -110,13 +125,45 @@ const styles: ComponentStyles<CheckboxClassNameContract, DesignSystem> = {
...
+            color: "ButtonText",
+        },
     },
     checkbox__checked: {
         "& $checkbox_stateIndicator": {
             "&::before": {
-                background: format("url('data:image/svg+xml;utf8,{0}')", indicatorSvg),
-                "@media (-ms-high-contrast:active)": {
-                    background: `url('data:image/svg+xml;utf8,${indicatorSvgHc}')`,
+                color: "green",
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/checkbox/index.ts]: removed

File: packages/fast-components-styles-msft/src/lightweight-button/index.ts [hunk 26]
```diff
@@ -46,20 +56,31 @@ const styles: ComponentStyles<LightweightButtonClassNameContract, DesignSystem>
...
+            ...applyHighContrastColorFill(),
         },
         "&:active:enabled": {
             color: accentForegroundActive,
             fill: accentForegroundActive,
             backgroundColor: "transparent",
         },
+        "a&": {
+            ...applyHighContrastHyperLink(),
+            "&$button__disabled": {
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/lightweight-button/index.ts]: adding :enabled does not work. this is targeting the content inside an anchor

File: packages/fast-components-styles-msft/src/card/index.ts [hunk 27]
```diff
@@ -13,6 +14,7 @@ const styles: ComponentStyles<CardClassNameContract, DesignSystem> = {
         ...applyElevatedCornerRadius(),
         ...applyElevation(ElevationMultiplier.e4),
         transition: "all 0.2s ease-in-out",
+        ...applyHighContrastTextBorder(),
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/card/index.ts]: The Card boundary, in high contrast, will be assigned the "Text" color. Having the border should not indicate the card as being interactive, or for decoration. The border will be helpful for organizing the UI.

File: packages/fast-components-styles-msft/src/action-trigger/index.ts [hunk 28]
```diff
@@ -42,18 +48,29 @@ const styles: ComponentStyles<ActionTriggerClassNameContract, DesignSystem> = {
     actionTrigger__primary: {
         "& $actionTrigger_glyph": {
             fill: accentForegroundCut,
+            ...applyHighContrastSelectedColorFill(),
+        },
+        "&:hover": {
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/action-trigger/index.ts]: added

File: packages/fast-components-styles-msft/src/action-toggle/index.ts [hunk 29]
```diff
@@ -52,18 +58,29 @@ const styles: ComponentStyles<ActionToggleClassNameContract, DesignSystem> = {
...
             fill: accentForegroundRest,
+            ...applyHighContrastColorFill(),
         },
         "&:hover": {
             "& $actionToggle_selectedGlyph, & $actionToggle_unselectedGlyph": {
                 fill: accentForegroundHover,
+                ...applyHighContrastColorFill(),
             },
         },
         "&:active": {
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/action-toggle/index.ts]: added to active too

File: packages/fast-components-styles-msft/src/action-toggle/index.ts [hunk 30]
```diff
@@ -52,18 +58,29 @@ const styles: ComponentStyles<ActionToggleClassNameContract, DesignSystem> = {
     actionToggle__primary: {
         "& $actionToggle_selectedGlyph, & $actionToggle_unselectedGlyph": {
             fill: accentForegroundCut,
+            ...applyHighContrastSelectedColorFill(),
+        },
+        "&:hover": {
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/action-toggle/index.ts]: added :enabled

File: packages/fast-components-styles-msft/src/accent-button/index.ts [hunk 31]
```diff
@@ -31,9 +47,33 @@ const styles: ComponentStyles<AccentButtonClassNameContract, DesignSystem> = {
...
+                ...applyHighContrastDisabledFill(),
+            },
+        },
         "& $button_beforeContent, & $button_afterContent": {
             fill: accentForegroundCut,
+            ...applyHighContrastSelectedColorFill(),
+        },
+        ...applyHighContrastAdjustSelectOutline(),
+        "a&": {
+            ...applyHighContrastHyperLink(),
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/accent-button/index.ts]: it effects the foreground only

File: packages/fast-components-styles-msft/src/accent-button/index.ts [hunk 32]
```diff
@@ -31,9 +47,33 @@ const styles: ComponentStyles<AccentButtonClassNameContract, DesignSystem> = {
...
+            "&$button__disabled": {
+                ...applyHighContrastDisabledBorder(),
+                "& $button_beforeContent, & $button_afterContent": {
+                    ...applyHighContrastDisabledFill(),
+                },
```
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/accent-button/index.ts]: I tried combining, but the glyphs were not taking the disabled color, but if i specified the before and after content it works

File: packages/fast-components-styles-msft/src/accent-button/index.ts (hunk 13 above)
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/accent-button/index.ts]: hover is still effecting the disabled state, that is why I had to set hover here

File: packages/fast-components-styles-msft/src/accent-button/index.ts [hunk 33]
```diff
@@ -11,6 +11,16 @@ import {
...
 } from "../utilities/color";
+import {
+    applyHighContrastAccentSelectedFillHover,
+    applyHighContrastAccentSelectedHover,
+    applyHighContrastAdjustSelectOutline,
+    applyHighContrastDisabledBorder,
+    applyHighContrastDisabledFill,
+    applyHighContrastDoubleFocus,
+    applyHighContrastHyperLink,
+    applyHighContrastSelectedColorFill,
```
Comment (janechu) [inline packages/fast-components-styles-msft/src/accent-button/index.ts]: Do these need to be functions? It seems like they could just be objects

File: packages/fast-components-styles-msft/src/action-toggle/index.ts [hunk 34]
```diff
@@ -73,23 +90,28 @@ const styles: ComponentStyles<ActionToggleClassNameContract, DesignSystem> = {
         },
         "&$actionToggle__disabled $actionToggle_selectedGlyph, &$actionToggle__disabled $actionToggle_unselectedGlyph": {
             fill: accentForegroundRest,
+            ...applyHighContrastDisabledFill(),
         },
     },
     actionToggle__justified: {
         "& $actionToggle_selectedGlyph, & $actionToggle_unselectedGlyph": {
             fill: accentForegroundRest,
```
Comment (nicholasrice) [inline packages/fast-components-styles-msft/src/action-toggle/index.ts]: It seems like there is a lot of duplication here - I'm concerned about how much code this is adding for a marginal use-case.

I'm wondering if we can reduce some of the duplication by using `!important`

File: packages/fast-components-styles-msft/src/accent-button/index.ts (hunk 33 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/accent-button/index.ts]: updated and converted to objects

File: packages/fast-components-styles-msft/src/action-toggle/index.ts (hunk 34 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/action-toggle/index.ts]: @nicholasrice  would like to sync with you more regarding this approach.

File: packages/fast-components-styles-msft/src/utilities/high-contrast.ts (hunk 20 above)
[the remark this answers is not in the document]
Comment (khamudom) [reply packages/fast-components-styles-msft/src/utilities/high-contrast.ts]: There are two types of border, one uses the button-text color and this particular one uses the text color.

File: packages/fast-components-styles-msft/src/action-toggle/index.ts (hunk 34 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/action-toggle/index.ts]: Made a pass to eliminate duplicated HC media queries, where possible. Surprising there we a lot, especially in our buttons.

**Comment by eljefe223** [comment]
Smoked to verify there were no regressions in the components in none HC mode.

File: packages/fast-components-styles-msft/src/utilities/high-contrast.ts [hunk 35]
```diff
@@ -0,0 +1,122 @@
...
+import { DesignSystem } from "../design-system";
+import { format, toPx } from "@microsoft/fast-jss-utilities";
+import { focusOutlineWidth, outlineWidth } from "./design-system";
+
+export const highContrastSelector: string = "@media (-ms-high-contrast:active)";
+
+export enum HighContrastColor {
+    text = "WindowText",
+    hyperLinks = "LinkText",
+    disabledText = "GrayText !important",
```
Comment (eljefe223) [inline packages/fast-components-styles-msft/src/utilities/high-contrast.ts]: is `!important` necessary for only this value? What about the others?

File: packages/fast-components-styles-msft/src/button/index.ts [hunk 36]
```diff
@@ -49,13 +58,16 @@ const applyTransparentBackplateStyles: CSSRules<DesignSystem> = {
         "& $button_contentRegion::before": {
             background: neutralForegroundRest,
             height: toPx<DesignSystem>(focusOutlineWidth),
+            [highContrastSelector]: {
+                background: "ButtonText",
```
Comment (bheston) [inline packages/fast-components-styles-msft/src/button/index.ts]: Looks like a couple of places that should use the constants.

File: packages/fast-components-styles-msft/src/utilities/high-contrast.ts (hunk 35 above)
Comment (bheston) [inline packages/fast-components-styles-msft/src/utilities/high-contrast.ts]: Should we just put important in all of them? It doesn't feel right to have it in only one, but I was thinking as I was going through that the string appeared a lot. Possibly either add an `important()` function or just include it by default in all HC colors.

Comment (khamudom) [reply packages/fast-components-styles-msft/src/utilities/high-contrast.ts]: Disabled should always trump all other values, when it is being used, in the style. So it always gets an !important, here, instead of having to repeat it in the const below.

Comment (khamudom) [reply packages/fast-components-styles-msft/src/utilities/high-contrast.ts]: That was the first thing I did, it didn't work. I am guessing it did not know which one to set !important to. That is why I set it in the const, when it needed it.

File: packages/fast-components-styles-msft/src/button/index.ts (hunk 36 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/button/index.ts]: thanks, added

File: packages/fast-components-styles-msft/src/button/index.ts [hunk 37]
```diff
@@ -111,18 +121,49 @@ const styles: ComponentStyles<ButtonClassNameContract, DesignSystem> = {
...
+            borderColor: "ButtonText",
+            color: "ButtonText",
+            fill: "ButtonText",
+            "-ms-high-contrast-adjust": "none",
+        },
+        "a&": {
+            "&$button__disabled": {
+                "&:hover": {
+                    ...highContrastDisabledBorder,
+                    "& $button_beforeContent, & $button_afterContent": {},
```
Comment (janechu) [inline packages/fast-components-styles-msft/src/button/index.ts]: if this is empty it seems like you can remove it

File: packages/fast-components-styles-msft/src/button/index.ts [hunk 38]
```diff
@@ -142,10 +188,18 @@ const styles: ComponentStyles<ButtonClassNameContract, DesignSystem> = {
                 toPx(focusOutlineWidth),
                 neutralFocusInnerAccent(accentFillRest)
             ),
+            ...highContrastDoubleFocus,
         }),
+        "&:disabled": {},
```
Comment (janechu) [inline packages/fast-components-styles-msft/src/button/index.ts]: why add this if it's empty?

File: packages/fast-components-styles-msft/src/button/index.ts [hunk 39]
```diff
@@ -180,7 +234,9 @@ const styles: ComponentStyles<ButtonClassNameContract, DesignSystem> = {
                 }
             ),
             borderColor: neutralFocus,
+            ...highContrastOutlineFocus,
         }),
+        "&:disabled": {},
```
Comment (janechu) [inline packages/fast-components-styles-msft/src/button/index.ts]: also here, empty object

File: packages/fast-components-styles-msft/src/call-to-action/index.ts [hunk 40]
```diff
@@ -105,10 +113,21 @@ const styles: ComponentStyles<CallToActionClassNameContract, DesignSystem> = {
...
     },
     callToAction__primary: {
         "& $callToAction_glyph": {
             fill: accentForegroundCut,
+            [highContrastSelector]: {
+                fill: "HighlightText !important",
+            },
+        },
+        "&:hover": {
+            "& $callToAction_glyph": {
```
Comment (janechu) [inline packages/fast-components-styles-msft/src/call-to-action/index.ts]: instead of doing a nested object you can combine these to `"&:hover $callToAction_glyph": {`

File: packages/fast-components-styles-msft/src/call-to-action/index.ts [hunk 41]
```diff
@@ -135,20 +155,23 @@ const styles: ComponentStyles<CallToActionClassNameContract, DesignSystem> = {
...
             "& $callToAction_glyph": {
                 fill: accentForegroundHover,
+                ...highContrastForeground,
             },
         },
         "&:active": {
-            "& $callToAction_glyph": {
-                fill: accentForegroundActive,
-            },
+            "& $callToAction_glyph": {},
```
Comment (janechu) [inline packages/fast-components-styles-msft/src/call-to-action/index.ts]: also here, you can remove this

File: packages/fast-components-styles-msft/src/patterns/button.ts [hunk 42]
```diff
@@ -1,13 +1,17 @@
...
-import { focusOutlineWidth, outlineWidth } from "../utilities/design-system";
+import { DesignSystem, ensureDesignSystemDefaults } from "../design-system";
 import { applyScaledTypeRamp } from "../utilities/typography";
 import { glyphSize, height, horizontalSpacing } from "../utilities/density";
 import { applyDisabledState } from "../utilities/disabled";
 import { ButtonBaseClassNameContract } from "@microsoft/fast-components-class-name-contracts-msft";
+import {
+    highContrastDisabledBorder,
+    highContrastDisabledForeground,
+} from "../utilities/high-contrast";
```
Comment (janechu) [inline packages/fast-components-styles-msft/src/patterns/button.ts]: it does not appear we are using any of these here, can you revert the changes to this file?

File: packages/fast-components-styles-msft/src/patterns/input-field.ts [hunk 43]
```diff
@@ -1,9 +1,8 @@
-import { horizontalSpacing } from "../utilities/density";
 import { CSSRules } from "@microsoft/fast-jss-manager";
+import { applyCornerRadius } from "../utilities/border";
 import { DesignSystem } from "../design-system";
-import { format, toPx } from "@microsoft/fast-jss-utilities";
+import { format, subtract, toPx } from "@microsoft/fast-jss-utilities";
```
Comment (janechu) [inline packages/fast-components-styles-msft/src/patterns/input-field.ts]: we do not appear to be using subtract, please remove

File: packages/fast-components-styles-msft/src/radio/index.ts [hunk 44]
```diff
@@ -102,13 +112,35 @@ const styles: ComponentStyles<RadioClassNameContract, DesignSystem> = {
...
-                "@media (-ms-high-contrast:active)": {
-                    backgroundColor: "ButtonHighlight",
+                [highContrastSelector]: {
+                    background: "Highlight",
+                },
+            },
+        },
+        "&:hover": {
+            "& $radio_stateIndicator": {
+                "&::before": {
```
Comment (janechu) [inline packages/fast-components-styles-msft/src/radio/index.ts]: instead of nesting things like this you con combine them to be `"&:hover $radio_stateIndicator::before"`

File: packages/fast-components-styles-msft/src/text-area/index.ts [hunk 45]
```diff
@@ -3,8 +3,8 @@ import { TextAreaClassNameContract } from "@microsoft/fast-components-class-name
 import { ComponentStyles, ComponentStyleSheet } from "@microsoft/fast-jss-manager";
 import { height } from "../utilities/density";
 import { inputFieldStyles } from "../patterns/input-field";
-import { multiply, toPx } from "@microsoft/fast-jss-utilities";
-import { designUnit } from "../utilities/design-system";
+import { format, multiply, toPx } from "@microsoft/fast-jss-utilities";
+import { designUnit, outlineWidth } from "../utilities/design-system";
```
Comment (janechu) [inline packages/fast-components-styles-msft/src/text-area/index.ts]: looks like you can remove these added imports

File: packages/fast-components-styles-msft/src/toggle/index.ts [hunk 46]
```diff
@@ -137,45 +145,60 @@ const styles: ComponentStyles<ToggleClassNameContract, DesignSystem> = {
...
         },
         "& $toggle_stateIndicator": {
             left: toPx(indicatorCheckedLeft),
             background: accentForegroundCut,
-            "@media (-ms-high-contrast:active)": {
-                background: "Background",
+            [highContrastSelector]: {
+                background: "HighlightText",
+                "&:hover": {
+                    [highContrastSelector]: {
```
Comment (janechu) [inline packages/fast-components-styles-msft/src/toggle/index.ts]: are you sure this nesting is right?i wouldn't think you could put a hover on the high contrast selector, and even if you could you wouldn't then need to re-declare the selector

Comment (khamudom) [reply packages/fast-components-styles-msft/src/toggle/index.ts]: weird, not sure why this didn't complain. updated to remove hover out of the high contrast selector

File: packages/fast-components-styles-msft/src/text-area/index.ts (hunk 45 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/text-area/index.ts]: removed

File: packages/fast-components-styles-msft/src/radio/index.ts (hunk 44 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/radio/index.ts]: combined

File: packages/fast-components-styles-msft/src/patterns/button.ts (hunk 42 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/patterns/button.ts]: reverted

File: packages/fast-components-styles-msft/src/call-to-action/index.ts (hunk 41 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/call-to-action/index.ts]: removed

File: packages/fast-components-styles-msft/src/button/index.ts (hunk 39 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/button/index.ts]: removed

File: packages/fast-components-styles-msft/src/button/index.ts (hunk 38 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/button/index.ts]: removed

File: packages/fast-components-styles-msft/src/button/index.ts (hunk 37 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/button/index.ts]: removed

File: packages/fast-components-styles-msft/src/text-area/index.ts (hunk 45 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/text-area/index.ts]: removed

File: packages/fast-components-styles-msft/src/button/index.ts (hunk 39 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/button/index.ts]: removed

File: packages/fast-components-styles-msft/src/call-to-action/index.ts (hunk 40 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/call-to-action/index.ts]: combined

File: packages/fast-components-styles-msft/src/patterns/input-field.ts (hunk 43 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/patterns/input-field.ts]: removed
