### PR TITLE
fix: increase specificity on MSFT styled components which are derived from other MSFT components

### LINKED ISSUE #1498: ensure MSFT components are not suseptible to specificity issues
We need to make sure component's we're exporting are not suseptible to the issues outlined in #1279
.

To do this, styled-compnents should never rely exclusivly on document order for CSS property specificity. If one component is overriding the style properties of another component, the overriding component should either:
a. Use jssStyleSheet props to override the styles on the component
b. Bolister specificity by adding seleectors (`.heading.heading__1` vs `.heading__1`)

### PR DESCRIPTION
**Pull request by chrisdholt**
closes #1498 
## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

## Process & policy checklist

- [x] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://microsoft.github.io/fast-dna/docs/en/contributing/standards) for this project.

### CODE REVIEW

File: packages/fast-components-styles-msft/src/paragraph/index.ts [hunk 1]
```diff
@@ -4,16 +4,20 @@ import { ParagraphClassNameContract } from "@microsoft/fast-components-class-nam
 import { fontWeight } from "../utilities/fonts";
 
 const styles: ComponentStyles<ParagraphClassNameContract, DesignSystem> = {
-    paragraph: {},
-    paragraph__1: {
-        fontWeight: `${fontWeight.semilight}`,
```
Comment (nicholasrice) [inline packages/fast-components-styles-msft/src/paragraph/index.ts]: I think you should actually leave these as-is, because otherwise they will have the oppertunity to override Heading

Comment (nicholasrice) [reply packages/fast-components-styles-msft/src/paragraph/index.ts]: Sorry thought this was Typography - you're good.
