### PR TITLE
fix: exit focus visible utility immediately with false value if DOM is unavailable

### LINKED ISSUE #2221: canUseFocusVisible throws exception during server side rendering
on line 17-19 the canUseDOM check should return false; currently the method continues and references the document.

### PR DESCRIPTION
**Pull request by chrisdholt**
closes #2221 

# Description

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

## Process & policy checklist

- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/en/contributing/standards) for this project.

### CODE REVIEW

File: packages/fast-web-utilities/src/dom.ts [hunk 1]
```diff
@@ -17,10 +17,10 @@ export function canUseFocusVisible(): boolean {
     }
 
     if (!canUseDOM()) {
```
Comment (nicholasrice) [inline packages/fast-web-utilities/src/dom.ts]: I think you still want to set `_canUseFocusVisible` to false so you avoid redundant `canUseDOM` calls

Comment (chrisdholt) [reply packages/fast-web-utilities/src/dom.ts]: @nicholasrice updated
