### PR TITLE
fix: high contrast for slider component

### LINKED ISSUE #1984: Track on slider is not visible in windows high contrast modes
**Describe the bug; what happened?**
Slider track bar and knob are not visible in high contrast mode, which results in an inaccessible experience. 

**What are the steps to reproduce the issue?**

Example:
1. Turn on windows high contrast
2. Open edge browser
3. Go to https://explore.fastdna.net/components/slider/
4. See that the track bar is not visible

**What behavior did you expect?**
The slider track bar and knob are both visible and map accordingly to HC colors

**If applicable, provide screenshots:**
slider_hc

### PR DESCRIPTION
**Pull request by khamudom**
# Description

Set high contrast media query to slider label tick mark. slider thumb (rest, hover and active state). The background and foreground of the slider track.

High contrast 1
image
High contrast 2
image
High contrast black
image
High contrast white
image

closes #1984 

## Motivation & context

When user turns on high contrast the slider does not show up

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/en/contributing/standards) for this project.

### CODE REVIEW

File: packages/fast-components-styles-msft/src/slider/index.ts [hunk 1]
```diff
@@ -70,18 +70,33 @@ const styles: ComponentStyles<SliderClassNameContract, DesignSystem> = {
         "&:active": {
             background: neutralForegroundActive,
         },
+        "@media (-ms-high-contrast:active)": {
+            background: "ButtonText",
+            "&:hover": {
+                background: "Highlight",
```
Comment (janechu) [inline packages/fast-components-styles-msft/src/slider/index.ts]: Seems like this is CSS2 keywords https://www.w3.org/TR/css-color-3/#css2-system

CSS2 keywords are marked as deprecated, why are we using them here?

File: packages/fast-components-styles-msft/src/slider/index.ts [hunk 2]
```diff
@@ -70,18 +70,33 @@ const styles: ComponentStyles<SliderClassNameContract, DesignSystem> = {
         "&:active": {
             background: neutralForegroundActive,
         },
+        "@media (-ms-high-contrast:active)": {
```
Comment (janechu) [inline packages/fast-components-styles-msft/src/slider/index.ts]: should this specify black-on-white or white-on-black? can you provide screenshots for both?

File: packages/fast-components-styles-msft/src/slider/index.ts (hunk 1 above)
Comment (nicholasrice) [reply packages/fast-components-styles-msft/src/slider/index.ts]: This is - AFAIK - the only way to tap into the Windows high contrast theme. This is what we do for all other components to support high contrast.

File: packages/fast-components-styles-msft/src/slider/index.ts (hunk 2 above)
Comment (khamudom) [reply packages/fast-components-styles-msft/src/slider/index.ts]: when you specify `-ms-high-contrast:active` it covers all high contrast styling rules, including black-on-white and white-on-black

File: packages/fast-components-styles-msft/src/slider/index.ts (hunk 1 above)
Comment (chrisdholt) [reply packages/fast-components-styles-msft/src/slider/index.ts]: Yeah, I think this is currently the design/mapping. This article by Greg Whitworth (MSFT Edge) lays it out in more detail: http://www.gwhitworth.com/blog/2017/04/how-to-use-ms-high-contrast/

Comment (khamudom) [reply packages/fast-components-styles-msft/src/slider/index.ts]: These keywords have been added as part of a new list of system colors.
https://github.com/w3c/csswg-drafts/issues/3804

Comment (janechu) [reply packages/fast-components-styles-msft/src/slider/index.ts]: Thanks, just wanted to get this on the record
