### PR TITLE
fix(fast-css-editor-react): update the api to accept strings for position

### LINKED ISSUE #706: Position should allow any valid CSS values
Currently the user can only put numbers, this does not accurately match what can be applied to these CSS properties.

This will cause a breaking change.

### PR DESCRIPTION
**Pull request by janechu**
Resolves #706

BREAKING CHANGE: The API for the fast-css-editor-react libraries CSSPosition and CSSEditor exports is changing to use strings instead of numbers for the left, right, top and bottom CSS properties. This is a fix needed to map directly to JSS and other CSS systems.

### CODE REVIEW

File: packages/fast-css-editor-react/app/app.tsx [hunk 1]
```diff
@@ -37,16 +37,16 @@ class App extends React.Component<{}, IAppState> {
             },
             editorExample: {
                 position: PositionValue.absolute,
-                left: 4,
-                top: 12
+                left: "4px",
```
Comment (nalogiudice) [inline packages/fast-css-editor-react/app/app.tsx]: Just curious, what happens if a user passes just "4" as a string?
