### PR TITLE
fix(fast-development-site) Move design kit link behind Site Menu

### LINKED ISSUE #14: Nested JSS classes without any css rules does not export the classname
### Expected behavior 
One should be able to nest a JSS class without defining root style rules
```
{
    root: {
        "& $nested: { color: "red" }
   },
   nested: {}
}
```
### Actual behavior
There is no class exposed under the `nested` key of the classes object.

### PR DESCRIPTION
**Pull request by eljefe223**
Closes #14 
 

For [details on formatting](https://github.com/Microsoft/fast-dna/wiki/pull-request-guidance) pull requests.

### CODE REVIEW

File: packages/fast-development-site-react/src/components/site/menu.tsx [hunk 1]
```diff
@@ -25,6 +26,9 @@ const style: ComponentStyles<ISiteNavManagedClasses, IDevSiteDesignSystem> = {
     },
     siteMenu_nav: {
         position: "absolute",
+        background: "#FFFFFF",
+        zIndex: "5",
+        boxShadow: `outline ${toPx(-2)} 0 ${toPx(4)} ${toPx(4)} rgba(0, 0, 0, 0.2)`,
```
Comment (nalogiudice) [inline packages/fast-development-site-react/src/components/site/menu.tsx]: We could use Chroma here to get the desired background boxshadow color.
`boxShadow: (config: IDesignSystem): string => {
      return `outline ${toPx(-2)} 0 ${toPx(4)} ${toPx(4)} ${Chroma(config.foregroundColor).alpha(0.2).css()}`;
  }`

Comment (chrisdholt) [reply packages/fast-development-site-react/src/components/site/menu.tsx]: I think with our overall goal of removing Chroma where we can (because we aren't using fast-colors yet), we should hold on this. We have quite a few places we could use it here, but I think we intentionally left off the dependency. We definitely need a better way to manipulate the colors here as most all of them are hard coded or built into the design system for single use cases. I think for now though, we should hold on using Chroma here and come up with a viable solution.
