### PR TITLE
fix: prevent default on tabs component navigation

### LINKED ISSUE #2610: Tabs component does not block scroll on up/down arrow keys navigation
The [tabs](https://github.com/microsoft/fast-dna/blob/master/packages/fast-components-react-base/src/tabs) component seems to provide support for up/down arrow key navigation, however, it does not block scroll in the page.

Please follow these steps to be able to repro:
1. Go to https://explore.edgewebui.net/FastMSFT/components/pivot
2. See the 'pivot' component uses the 'tabs' component.
3. Either update the 'pivot' container height in the dom or make screen small enough to have scroll in the page.
4. Click on any tab, and then start navigating using up/down arrow keys.

Expected behavior: no scroll happens

### PR DESCRIPTION
**Pull request by chrisdholt**
# Description
closes #2610 

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

## Process & policy checklist

- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/en/contributing/standards) for this project.

### CODE REVIEW

File: packages/fast-components-react-base/src/tabs/tabs.tsx [hunk 1]
```diff
@@ -318,10 +318,13 @@ class Tabs extends Foundation<TabsHandledProps, TabsUnhandledProps, TabsState> {
...
+                e.preventDefault();
                 this.activateTab(TabLocation.previous);
                 break;
             case keyCodeArrowRight:
             case keyCodeArrowDown:
+                e.preventDefault();
+
                 this.activateTab(TabLocation.next);
                 break;
             case keyCodeHome:
```
Comment (prabashn) [inline packages/fast-components-react-base/src/tabs/tabs.tsx]: Didn't even know about the home/end buttons... that's neat. In windows you get scroll up down due to these as well, should you be doing the same for those as well?

Comment (chrisdholt) [reply packages/fast-components-react-base/src/tabs/tabs.tsx]: interesting - is it windows specific?

Comment (prabashn) [reply packages/fast-components-react-base/src/tabs/tabs.tsx]: Although, I'm not sure if taking over those two buttons even while within the tabs control is necessarily a good thing.

Comment (prabashn) [reply packages/fast-components-react-base/src/tabs/tabs.tsx]: > interesting - is it windows specific?

Don't know -- that's all I have access to now. By scroll up/down, I mean "home"=scroll to the top of the document, and "end"=scroll to the end of the document.

Since these are standard buttons we (I) use in windows to reach the top/end, maybe not take over these, as it could become annoying.

Comment (chrisdholt) [reply packages/fast-components-react-base/src/tabs/tabs.tsx]: Yep, that's my bent here too; thx @prabashn!
