### PR TITLE
fix: remove external margin, padding, and fix RTL micro-interaction on MSFT call to action

### LINKED ISSUE #1048: MSFT call to action component is visually broken

### PR DESCRIPTION
**Pull request by chrisdholt**
<body>
closes #1048 
<footer>
 

For [details on formatting](https://github.com/Microsoft/fast-dna/wiki/pull-request-guidance) pull requests.

### CODE REVIEW

File: packages/fast-components-styles-msft/src/call-to-action/index.ts [hunk 1]
```diff
@@ -34,7 +31,10 @@ export const callToActionButtonOverrides: ComponentStyles<
     button__primary: {
         "&:hover": {
             "& $button_contentRegion": {
-                [applyLocalizedProperty("left", "right", Direction.ltr)]: "-4px",
+                left: (config: DesignSystem): string => {
```
Comment (nicholasrice) [inline packages/fast-components-styles-msft/src/call-to-action/index.ts]: I noticed the animation of these is pretty janky also - switching to a transform makes it much smoother. If you don't want to change in this PR I can file a task for a follow up but thought it might be within scope - your call.

Comment (chrisdholt) [reply packages/fast-components-styles-msft/src/call-to-action/index.ts]: May as well do with these changes. CTA is completely broken right now as it is, so I'd say it's definitely in scope

File: packages/fast-components-styles-msft/src/call-to-action/index.ts [hunk 2]
```diff
@@ -91,10 +93,8 @@ const styles: ComponentStyles<CallToActionClassNameContract, DesignSystem> = (
             width: "8px",
             [applyLocalizedProperty("marginLeft", "marginRight", direction)]: "6px",
             transform: direction === Direction.ltr ? "none" : "rotate(180deg)",
-            verticalAlign: "top",
             transition: "all 600ms cubic-bezier(0.19, 1, 0.22, 1)",
-            left: "0",
-            marginTop: "4px",
+            marginTop: direction === Direction.ltr ? "4px" : "0",
```
Comment (nicholasrice) [inline packages/fast-components-styles-msft/src/call-to-action/index.ts]: Why is he `marginTop` value concerned with document direction?

File: packages/fast-components-styles-msft/src/call-to-action/index.ts [hunk 3]
```diff
@@ -65,21 +67,21 @@ const styles: ComponentStyles<CallToActionClassNameContract, DesignSystem> = (
...
-            marginTop: "16px",
             transition: "all 0.2s ease-in-out",
             "&:hover, &:focus": {
                 outline: "none",
                 "& $callToAction_glyph": {
-                    left: "8px",
+                    transform:
+                        direction === Direction.ltr
+                            ? "translateX(4px)"
+                            : "rotate(180deg) translateX(4px)",
```
Comment (nicholasrice) [inline packages/fast-components-styles-msft/src/call-to-action/index.ts]: should translate be `-4px`?

Comment (chrisdholt) [reply packages/fast-components-styles-msft/src/call-to-action/index.ts]: @nicholasrice can you pull down? it seems odd, but this was actually working as expected...

File: packages/fast-components-styles-msft/src/call-to-action/index.ts (hunk 2 above)
Comment (chrisdholt) [reply packages/fast-components-styles-msft/src/call-to-action/index.ts]: RTL is weird.

File: packages/fast-components-styles-msft/src/call-to-action/index.ts (hunk 3 above)
Comment (nicholasrice) [reply packages/fast-components-styles-msft/src/call-to-action/index.ts]: yep, thats... not what I expected. Looks good!
