### PR TITLE
fix: adds proper RTL styles for toggle state indicator

### LINKED ISSUE #2251: Toggle component should change selected direction in RTL
The toggle component should change the selected/unselected direction in RTL. Since this is a component where direction and color indicates state, it should change in RTL mode. This is similar to how the slider component changes the className to sliderLabel__rtl in RTL mode.

### PR DESCRIPTION
**Pull request by nicholasrice**
# Description
Adds RTL styles for state indicator of toggle.
image

fixes #2251

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/en/contributing/standards) for this project.

### CODE REVIEW

File: packages/fast-components-styles-msft/src/toggle/index.ts [hunk 1]
```diff
@@ -178,7 +179,8 @@ const styles: ComponentStyles<ToggleClassNameContract, DesignSystem> = {
             },
         },
         "& $toggle_stateIndicator": {
-            left: toPx(indicatorCheckedLeft),
+            left: directionSwitch(toPx(indicatorCheckedLeft), "unset"),
+            right: directionSwitch("unset", toPx(indicatorCheckedLeft)),
```
Comment (bekell) [inline packages/fast-components-styles-msft/src/toggle/index.ts]: Maybe rename this to indicatorChecked since its not always on the left?
