### PR TITLE
fix: update broken links after migrated msft-docs to explore

### LINKED ISSUE #1379: Broken Link to Components page in Documentation
Components link leads to an error page "Error 403 - This web app is stopped"

1) go to https://microsoft.github.io/fast-dna/docs/en/contributing/install (dev documentation link from the readme)
2) click the components link in the top right corner

image

### PR DESCRIPTION
**Pull request by awentzel**
# Description
Update to fix broken links

This will be merged after the new links are up and running pending approval on https://explore-stage.fastdna.net 

## Motivation & context
resolves #1379 

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [x] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://microsoft.github.io/fast-dna/docs/en/contributing/standards) for this project.

### CODE REVIEW

File: build/testing/applitools/run-msft-docs.js [hunk 1]
```diff
@@ -7,9 +7,9 @@ let spawn = require("child_process").spawnSync;
  */
 class Config {
     constructor() {
-        this.domainName = "https://msft-docs.fast-dna.net";
-        this.appName = "FAST-DNA";
-        this.siteName = "MSFT Doc Site";
+        this.domainName = "https://explore.fastdna.net";
+        this.appName = "FASTDNA";
```
Comment (chrisdholt) [inline build/testing/applitools/run-msft-docs.js]: Can you give me a rundown on changing the hyphenation here?

Comment (awentzel) [reply build/testing/applitools/run-msft-docs.js]: In most new resources (domains, sites, etc) we're going with fastdna instead of the use of hyphens.  In the Name i'm not sure this is true. But, absolutely in pathing per @Falkicon.

Comment (chrisdholt) [reply build/testing/applitools/run-msft-docs.js]: I get the pathing - that makes sense. Our name everywhere is hyphenated, so I feel like we should probably confirm that *is not* changing ASAP so we can be consistent with branding.
