### PR TITLE
fix(fast-web-utilities): fix an issue where getClientRectWithMargin threw an error in EDGE and IE strict modes due to readonly properties

### LINKED ISSUE #764: Element.getBoundingClientRect return value is read-only
It looks like this is the offending line:
https://github.com/Microsoft/fast-dna/blob/master/packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx#L116

### PR DESCRIPTION
**Pull request by chrisdholt**
closes #764 
<body>

<footer>
 

For [details on formatting](https://github.com/Microsoft/fast-dna/wiki/pull-request-guidance) pull requests.

### CODE REVIEW

File: packages/fast-web-utilities/src/html.ts [hunk 1]
```diff
@@ -1,13 +1,30 @@
...
-export function getClientRectWithMargin(element: HTMLElement): ClientRect | DOMRect {
+export function getClientRectWithMargin(element: HTMLElement): IClientRectWithMargin {
     if (!element) {
         return;
     }
 
-    const clone: any = element.getBoundingClientRect();
+    const rect: ClientRect = element.getBoundingClientRect();
     const style: CSSStyleDeclaration = window.getComputedStyle(element, null);
+    const clone: any = {
```
Comment (nalogiudice) [inline packages/fast-web-utilities/src/html.ts]: should this typing be `any` ?

Comment (chrisdholt) [reply packages/fast-web-utilities/src/html.ts]: updated.
