### PR TITLE
fix: ensure onClick and onKeyDown unhandledProps on ContextMenuItem are triggered as expected

### LINKED ISSUE #1260: onClick is getting eaten in context-menu-item
**Description**
When using the ContextMenuItem component if a dev specifies onClick that event handler is never invoked

**Repro steps**
create an instance of ContextMenuItem and attempt to set an onClick handler:
                 
```
<ContextMenuItem
                        className={this.props.managedClasses.contextMenuItem}
                        onClick={(event: React.MouseEvent<HTMLDivElement>): void => {
                            console.log("test");
                        }}
>Test
</ContextMenuItem>
```

In the code below from context-menu-item.tsx the dev's onClick is passed in as unhandledProps and then an onClick is specified on the div effectively eating the dev's onClick.

```
public render(): React.ReactElement<HTMLDivElement> {
        return (
            <div
                {...this.unhandledProps()}
                className={this.generateClassNames()}
                role={this.props.role}
                aria-disabled={this.props.disabled || undefined}
                onKeyDown={this.handleMenuItemKeyDown}
                onClick={this.handleMenuItemClick}
            >
                {this.props.children}
            </div>
        );
    }
```

### PR DESCRIPTION
**Pull request by nicholasrice**
# Description

`onClick` and `onKeyDown` unhandled props were being clobbered by props applied internally by the `ContextMenuItem`, which caused these event handlers to never get called. This PR ensures those unhandled prop callbacks work as epxcted

fixes #1260
## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

## Process & policy checklist

- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://microsoft.github.io/fast-dna/docs/en/contributing/standards) for this project.

### CODE REVIEW

File: packages/fast-components-react-base/src/context-menu-item/context-menu-item.tsx [hunk 1]
```diff
@@ -87,30 +87,30 @@ class ContextMenuItem extends Foundation<
...
+        if (typeof this.props.onInvoke === "function" && !this.props.disabled) {
             switch (e.keyCode) {
                 case KeyCodes.enter:
                 case KeyCodes.space:
                     this.props.onInvoke(e, this.props);
                     break;
             }
         }
+
+        if (typeof this.props.onKeyDown === "function") {
```
Comment (chrisdholt) [inline packages/fast-components-react-base/src/context-menu-item/context-menu-item.tsx]: Do we want to execute this if the item is disabled?

File: packages/fast-components-react-base/src/context-menu-item/context-menu-item.tsx [hunk 2]
```diff
@@ -87,30 +87,30 @@ class ContextMenuItem extends Foundation<
...
     private handleMenuItemClick = (e: React.MouseEvent<HTMLDivElement>): void => {
-        if (this.props.disabled) {
-            return;
+        if (typeof this.props.onInvoke === "function" && !this.props.disabled) {
+            this.props.onInvoke(e, this.props);
         }
 
-        if (typeof this.props.onInvoke === "function") {
-            this.props.onInvoke(e, this.props);
+        if (typeof this.props.onClick === "function") {
```
Comment (chrisdholt) [inline packages/fast-components-react-base/src/context-menu-item/context-menu-item.tsx]: Do we want to execute this if disabled? I could potentially see a reason, but wonder if it's counterintuitive.

File: packages/fast-components-react-base/src/context-menu-item/context-menu-item.tsx [hunk 3]
```diff
@@ -87,30 +87,30 @@ class ContextMenuItem extends Foundation<
...
             switch (e.keyCode) {
                 case KeyCodes.enter:
                 case KeyCodes.space:
                     this.props.onInvoke(e, this.props);
                     break;
             }
         }
+
+        if (typeof this.props.onKeyDown === "function") {
+            this.props.onKeyDown(e);
```
Comment (chrisdholt) [inline packages/fast-components-react-base/src/context-menu-item/context-menu-item.tsx]: Assuming we are only sending the event because it's implicit and we aren't defining a contract to enumerate what we are sending back?

File: packages/fast-components-react-base/src/context-menu-item/context-menu-item.tsx (hunk 1 above)
Comment (nicholasrice) [reply packages/fast-components-react-base/src/context-menu-item/context-menu-item.tsx]: yes - this should work as an unhandledProp.

File: packages/fast-components-react-base/src/context-menu-item/context-menu-item.tsx (hunk 2 above)
Comment (nicholasrice) [reply packages/fast-components-react-base/src/context-menu-item/context-menu-item.tsx]: yes - this should work as an unhandledProp.

File: packages/fast-components-react-base/src/context-menu-item/context-menu-item.tsx (hunk 3 above)
Comment (nicholasrice) [reply packages/fast-components-react-base/src/context-menu-item/context-menu-item.tsx]: The contract is defined in `unhandledProps`
