### PR TITLE
fix: add additional wrapper to dialog to prevent subpixel aliasing due to css transforms

### LINKED ISSUE #1339: Blurry content in Dialog component
In some cases the content of a dialog, text in particular, can be blurry.  This is because of issues with using transform: translate to position the dialog.

We noticed the issue with the print dialog in a prototype which had a window positioned with a transform hosting a dialog, also positioned with a transform.  The problem was fixed by overriding styles and using css styling other than transform to position the dialog's content region.  

We should investigate whether we can improve the dialog component so that this is not an issue developers have to deal with.

### LINKED ISSUE #1399: Document handled vs unhandled prop guidance
We need clear documentation on when a prop is handled vs unhandled. Documentation should clearly communicate the criteria that makes a prop handled:
- Any HTML attribute name that is required (in general we should avoid HTML attribute names)
  - id, title, etc 
- Any prop name that is not a valid HTML attribute
- Any HTML attribute not applied to the HTML element populated with `unhandledProps()` - for instance, `value` of checkbox where the root of the `Checkbox` component is actually a `div`

We should also clearly document the unhandledProps()` mechanism and it's intended use.

### PR DESCRIPTION
**Pull request by chrisdholt**
closes #1339 (not 99...)

I don't believe this is a breaking change as the API is not affected. It does add a new div wrapper and class name contract, but the styled component remains centered.

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [x] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

## Process & policy checklist

- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://microsoft.github.io/fast-dna/docs/en/contributing/standards) for this project.

### CODE REVIEW

File: packages/fast-components-class-name-contracts-base/src/dialog/index.ts [hunk 1]
```diff
@@ -7,6 +7,11 @@ export interface DialogClassNameContract {
      */
     dialog?: string;
 
+    /**
+     * The wrapper of the dialog contents
+     */
+    dialog_wrapper?: string;
```
Comment (janechu) [inline packages/fast-components-class-name-contracts-base/src/dialog/index.ts]: should we be more specific to what is being wrapped? for example "dialog_contentRegionWrapper"
