### PR TITLE
fix: explicitly apply an additional active prop to Tab and TabPanel via the Tabs component instead of using unhandledProps

### LINKED ISSUE #958: Tab uses unhandledProps as part of it's code logic when it shouldn't
The tab component accesses the `aria-selected` property of unhandled props to descide if it should be active or not. This should instead be handled by a handled "active" (or some similar name) and should not have explicit behavior based on unhandledProps

### PR DESCRIPTION
**Pull request by janechu**
Resolves #958

### CODE REVIEW

**Comment by janechu** [comment]
@chrisdholt these tests are already in place.

File: packages/fast-components-react-base/src/tabs/tab.tsx [hunk 1]
```diff
@@ -9,10 +9,15 @@ class Tab extends Foundation<
     ITabUnhandledProps,
     {}
 > {
+    public static defaultProps: Partial<ITabHandledProps> = {
```
Comment (nicholasrice) [inline packages/fast-components-react-base/src/tabs/tab.tsx]: `defaultProps` should be `Partial<TabProps>` - defaultProps are always a partial of the comprehensive prop object.

File: packages/fast-components-react-base/src/tabs/tab-panel.tsx [hunk 2]
```diff
@@ -9,10 +9,15 @@ class TabPanel extends Foundation<
     ITabPanelUnhandledProps,
     {}
 > {
+    public static defaultProps: Partial<ITabPanelHandledProps> = {
```
Comment (nicholasrice) [inline packages/fast-components-react-base/src/tabs/tab-panel.tsx]: `Partial<TabPanelProps>`
