### PR TITLE
fix(fast-components-styles-msft): remove duplicate code and creates a utility to apply mixed colors

### LINKED ISSUE #447: Fix "identical-code" issue in packages/fast-components-styles-msft/src/text-field/index.ts
Identical blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-components-styles-msft/src/text-field/index.ts#issue_5afc65c7742c760001000252

Remove duplication by moving the color utility function into it's own file.

### PR DESCRIPTION
**Pull request by chrisdholt**
<body>

<footer>
 closes #447 

For [details on formatting](https://github.com/Microsoft/fast-dna/wiki/pull-request-guidance) pull requests.

### CODE REVIEW

File: packages/fast-components-styles-msft/src/utilities/colors.ts [hunk 1]
```diff
@@ -0,0 +1,6 @@
+import * as Chroma from "chroma-js";
+import { IDesignSystem } from "../design-system";
```
Comment (janechu) [inline packages/fast-components-styles-msft/src/utilities/colors.ts]: doesn't appear to be getting used
