### PR TITLE
fix: canUsedForcedColors should be called canUseForcedColors

### LINKED ISSUE #2380: Typo: canUsedForcedColors should be called canUseForcedColors
Typo in canUsedForcedColors name, should be canUseForcedColors (i.e. canUse instead of canUsed).

From this change: https://github.com/microsoft/fast-dna/commit/125a85c89049f5e1d1ce6313525ea454842c8e46

image

### PR DESCRIPTION
**Pull request by khamudom**
There is a typo on canUsedForcedColors. It should be called canUseForcedColors

# Description

deprecated and replaced `canUsedForcedColors`

## Motivation & context

close #2380 

## Issue type checklist

- [ ] **Chore**: A change that does not impact distributed packages.
- [ ] **Bug fix**: A change that fixes an issue, link to the issue above.
- [ ] **New feature**: A change that adds functionality.

**Is this a breaking change?**
- [ ] This change causes current functionality to break.

## Process & policy checklist

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-dna/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/en/contributing/standards) for this project.

### CODE REVIEW

File: packages/fast-web-utilities/src/dom.ts [hunk 1]
```diff
@@ -55,10 +55,17 @@ export function canUseCssGrid(): boolean {
...
         canUseDOM() &&
         (window.matchMedia("(forced-colors: none)").matches ||
             window.matchMedia("(forced-colors: active)").matches)
     );
 }
+
+/**
+ * @deprecated Use 'canUseForcedColors' instead
+ */
+export function canUsedForcedColors(): boolean {
```
Comment (nicholasrice) [inline packages/fast-web-utilities/src/dom.ts]: you can simply assign this - 

`export const canUsedForcedColors: typeof canUseForcedColors = canUseForcedColors;`

Comment (khamudom) [reply packages/fast-web-utilities/src/dom.ts]: updated
