### PR TITLE
fix: correct and standardize component interfaces across react

### LINKED ISSUE #947: Some components do not implement prop interfaces correctly
Certain components aren't implementing prop interfaces correctly, such as unhandledProp interfaces not being used. Ensure all interfaces are implemented correctly

### PR DESCRIPTION
**Pull request by nicholasrice**
closes #947

### CODE REVIEW

File: packages/fast-components-react-msft/src/subheading/subheading.tsx [hunk 1]
```diff
@@ -5,44 +5,45 @@ import {
...
+    protected handledProps: HandledProps<ISubheadingHandledProps> = {
         size: void 0,
         managedClasses: void 0,
         tag: void 0
     };
 
     private get size(): TypographySize {
         switch (this.props.size) {
-            case SubheadingLevel._1:
+            case SubheadingSize._1:
```
[the remark this answers is not in the document]
Comment (nicholasrice) [reply packages/fast-components-react-msft/src/subheading/subheading.tsx]: yes

File: packages/fast-components-react-msft/webpack.config.js [hunk 2]
```diff
@@ -46,9 +43,6 @@ module.exports = (env, args) => {
             ]
         },
         plugins: [
-            new ForkTsCheckerWebpackPlugin({
```
Comment (janechu) [inline packages/fast-components-react-msft/webpack.config.js]: need to remove this import and from the package.json

File: packages/fast-components-react-base/src/dialog/dialog.props.ts [hunk 3]
```diff
@@ -53,7 +55,4 @@ export interface IDialogHandledProps {
     visible?: boolean;
 }
 
-export type DialogOnDismiss = (e?: React.MouseEvent | KeyboardEvent) => void;
-export interface IDialogUnhandledProps extends React.HTMLAttributes<HTMLDivElement> {}
-export interface IDialogManagedClasses extends IManagedClasses<IDialogClassNameContract> {}
 export type DialogProps = IDialogHandledProps & IDialogUnhandledProps & IDialogManagedClasses;
```
[the remark this answers is not in the document]
Comment (nicholasrice) [reply packages/fast-components-react-base/src/dialog/dialog.props.ts]: yep - good catch

File: packages/fast-components-react-base/src/hypertext/hypertext.props.ts [hunk 4]
```diff
@@ -13,6 +15,4 @@ export interface IHypertextHandledProps {
     children?: React.ReactNode | React.ReactNode[];
```
Comment (chrisdholt) [inline packages/fast-components-react-base/src/hypertext/hypertext.props.ts]: @nicholasrice looks like this one got missed

File: packages/fast-components-react-base/src/button/button.props.ts [hunk 5]
```diff
@@ -1,11 +1,13 @@
 import * as React from "react";
 import { IButtonClassNameContract, IManagedClasses } from "@microsoft/fast-components-class-name-contracts-base";
 
-export interface IButtonHandledProps {
+export interface IButtonManagedClasses extends IManagedClasses<IButtonClassNameContract> {}
+export interface IButtonUnhandledProps extends React.AllHTMLAttributes<HTMLElement> {}
```
Comment (nalogiudice) [inline packages/fast-components-react-base/src/button/button.props.ts]: Wondering why this couldn't be `HTMLAnchorElement | HTMLButtonElement`

Comment (chrisdholt) [reply packages/fast-components-react-base/src/button/button.props.ts]: At the time the two of those were considered mutually exclusive via TS and would throw a compile error. It may be updated now, but we'd have to look into typescript updates to confirm.
